---
- name: create_dhcp_configs
  template: src=dhcp_node.conf dest="/etc/dhcp/dhcpd.d/nodes.conf"
  notify:
    - restart dhcpd

- name: create_pxe_boot_data
  template: src=pxe_node.conf dest="/var/www/provision/nodes/{{ item }}.conf"
  with_items: groups['pxe_bootable_nodes']
