---
#TODO: Combine pxe_*, dhcp and dnsmasq roles
- name: make sure dhcp dir exists
  file: "path=/etc/dhcp/dhcpd.d state=directory"

- name: install dhcp server
  yum: pkg=dhcp state=installed

##
# Installing httpd is also in pxe_bootstrap
# Installing dnsmasq is also in ansible-role-dnsmasq
# Here to make this role independent.
- name: install httpd server
  yum: pkg=httpd state=installed
- name: install dnsmasq server
  yum: pkg=dnsmasq state=installed

- name: create_dhcp_configs
  template: src=dhcp_node.conf dest="/etc/dhcp/dhcpd.d/nodes.conf"
  notify:
    - restart dhcpd
##
# This task is also in pxe_bootstrap
- name: create_pxe_directory_structure
  file: path=/var/www/provision/nodes state=directory owner=apache group=apache mode="0755"

- name: create pxe boot data json file
  template: src='pxe_nodes.json.j2' dest='/var/www/provision/nodes/pxe_nodes.json'

- name: populate hosts file from template with PXE hosts
  template: src='hosts.j2' dest='{{ hosts_file_to_populate }}' owner=root group=root mode='0644'
  notify:
    - restart dnsmasq
  tags: dns_update

##
# Use a custom script to parse the inventory file because there's no easy way to list the groups in a group of groups using ansible built-in variables.

- name: grab a list of the groups
  command: python files/custom-inventory.py --list --json --inventory {{ hosts_file_inventory_location }}
  register: reg_inventory
  changed_when: False
  delegate_to: localhost

- name: store list of groups in a fact as json
  set_fact: my_inventory="{{ reg_inventory['stdout']|from_json }}"

- name: store the list of groups in a group in a fact
  set_fact: my_group="{{ my_inventory['pxe_bootable_nodes']}}"

- name: print each group in the group
  debug: var=item
  with_items: "{{ my_group }}"

- name: copy over kickstart file
  template: src="kickstart.cfg" dest="{{ ksBootSrvDir }}/{{ hostvars[item].kickstart_profile }}" owner=apache group=apache mode=0644
  with_items: "{{ groups.pxe_bootable_nodes }}"
