---
#TODO: Combine pxe_*, dhcp and dnsmasq roles
- name: make sure dhcp dir exists
  file: "path=/etc/dhcp/dhcpd.d state=directory"

- name: install dhcp server
  yum: pkg=dhcp state=installed

##
# Installing httpd is also in pxe_bootstrap
# Here to make this role independent so it can be tested
- name: install httpd server
  yum: pkg=httpd state=installed

- name: create_dhcp_configs
  template: src=dhcp_node.conf dest="/etc/dhcp/dhcpd.d/nodes.conf"
  notify:
    - restart dhcpd
##
# This task is also in pxe_bootstrap
- name: create_pxe_directory_structure
  file: path=/var/www/provision/nodes state=directory owner=apache group=apache mode="0755"

- name: create_pxe_boot_data
  template: src=pxe_node.conf dest="/var/www/provision/nodes/{{ hostvars[item].pxe_name }}.conf"
  with_items: groups.pxe_bootable_nodes

- name: populate /etc/hosts file with PXE hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ip_address }} {{ hostvars[item].pxe_name }} {{ hostvars[item].pxe_name }}.{{ intDomain }}.{{ siteDomain }}" state=present
  when: hostvars[item].ip_address is defined
  with_items: groups.pxe_bootable_nodes
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate /etc/hosts file with PXE hosts-ib IP addresses
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}-ib.{{ intDomain }}.{{ siteDomain }}$' line="{{ hostvars[item].ib_ip_addr }} {{ hostvars[item].pxe_name }}-ib {{ hostvars[item].pxe_name }}-ib.{{ intDomain }}.{{ siteDomain }}" state=present
  when: hostvars[item].ib_ip_addr is defined
  with_items: groups.pxe_bootable_nodes
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate /etc/hosts file with the admin host's internal address
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].int_ip_addr }} {{ siteName }}-admin {{item}}" state=present
  when: hostvars[item].int_ip_addr is defined
  with_items: groups.admin
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate /etc/hosts file with the grid host's internal address
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].int_ip_addr }} {{ siteName }}-grid {{item}}" state=present
  when: hostvars[item].int_ip_addr is defined
  with_items: groups.grid
  notify:
    - restart dnsmasq
  tags: dns_update

- name: copy over kickstart file
  template: src="kickstart.cfg" dest="{{ ksBootSrvDir }}/{{ hostvars[item].kickstart_profile }}" owner=apache group=apache mode=0644
  with_items: groups.pxe_bootable_nodes
