---
#TODO: Combine pxe_*, dhcp and dnsmasq roles
- name: make sure dhcp dir exists
  file: "path=/etc/dhcp/dhcpd.d state=directory"

- name: install dhcp server
  yum: pkg=dhcp state=installed

##
# Installing httpd is also in pxe_bootstrap
# Installing dnsmasq is also in ansible-role-dnsmasq
# Here to make this role independent.
- name: install httpd server
  yum: pkg=httpd state=installed
- name: install dnsmasq server
  yum: pkg=dnsmasq state=installed

- name: create_dhcp_configs
  template: src=dhcp_node.conf dest="/etc/dhcp/dhcpd.d/nodes.conf"
  notify:
    - restart dhcpd
##
# This task is also in pxe_bootstrap
- name: create_pxe_directory_structure
  file: path=/var/www/provision/nodes state=directory owner=apache group=apache mode="0755"

- name: create pxe boot data json file
  template: src='pxe_nodes.json.j2' dest='/var/www/provision/nodes/pxe_nodes.json'

- name: populate hosts file from template with PXE hosts
  template: src='hosts.j2' dest='{{ hosts_file_to_populate }}' owner=root group=root mode='0644'
  notify:
    - restart dnsmasq
  tags: dns_update

##
# Use a custom script to parse the inventory file because there's no easy way to list the groups in a group of groups using ansible built-in variables.

- name: grab a list of hosts (one per child group in {{ hosts_file_group_to_populate }}) using custom-inventory.py
  command: python files/custom-inventory.py --single --json --group {{ hosts_file_group_to_populate }} --inventory {{ hosts_file_inventory_location }}
  register: reg_inventory
  changed_when: False
  delegate_to: localhost
  always_run: True

- name: store the list of hosts as json in a variable called hosts_file_my_inventory
  set_fact: hosts_file_my_inventory="{{ reg_inventory['stdout']|from_json }}"

- name: set the list of hosts as a fact called hosts_file_my_group - from key {{ hosts_file_group_to_populate }} in hosts_file_my_inventory
  set_fact: hosts_file_my_group="{{ hosts_file_my_inventory['{{ hosts_file_group_to_populate }}']}}"

- name: print each host
  debug: var=item
  with_items: "{{ hosts_file_my_group }}"

- name: copy over kickstart file
  template: src="kickstart.cfg" dest="{{ ksBootSrvDir }}/{{ hostvars[item].kickstart_profile }}" owner=apache group=apache mode=0644
  with_items: "{{ hosts_file_my_group }}"
