---
#TODO: Combine pxe_*, dhcp and dnsmasq roles
- name: make sure dhcp dir exists
  file: "path=/etc/dhcp/dhcpd.d state=directory"

- name: install dhcp server
  yum: pkg=dhcp state=installed

##
# Installing httpd is also in pxe_bootstrap
# Installing dnsmasq is also in ansible-role-dnsmasq
# Here to make this role independent.
- name: install httpd server
  yum: pkg=httpd state=installed
- name: install dnsmasq server
  yum: pkg=dnsmasq state=installed

- name: create_dhcp_configs
  template: src=dhcp_node.conf dest="/etc/dhcp/dhcpd.d/nodes.conf"
  notify:
    - restart dhcpd
##
# This task is also in pxe_bootstrap
- name: create_pxe_directory_structure
  file: path=/var/www/provision/nodes state=directory owner=apache group=apache mode="0755"

- name: create_pxe_boot_data
  template: src=pxe_node.conf dest="/var/www/provision/nodes/{{ hostvars[item].pxe_name }}.conf"
  with_items: "{{ groups.pxe_bootable_nodes }}"

- name: populate hosts file from template with PXE hosts
  template: src='hosts.j2' dest='{{ hosts_file_to_populate }}' owner=root group=root mode='0644'
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate hosts file with the admin host's internal address
  lineinfile: 
        dest='{{ hosts_file_to_populate }}'
        regexp='^{{ hostvars[item].int_ip_addr }} {{ siteName }}-admin {{item}} {{ siteName }}-admin.{{ intDomain }}.{{ siteDomain }}$' 
        line="{{ hostvars[item].int_ip_addr }} {{ siteName }}-admin {{item}} {{ siteName }}-admin.{{ intDomain }}.{{ siteDomain }}" 
        state=present
  when: hostvars[item].int_ip_addr is defined and hosts_file_admin_group_to_populate != ""
  with_items: "{{ hosts_file_admin_group_to_populate }}"
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate hosts file with the grid host's internal address
  lineinfile: 
        dest='{{ hosts_file_to_populate }}'
        regexp='^{{ hostvars[item].int_ip_addr }} {{ siteName }}-grid {{item}} {{ siteName }}-grid.{{ intDomain }}.{{ siteDomain }}$' 
        line="{{ hostvars[item].int_ip_addr }} {{ siteName }}-grid {{item}} {{ siteName }}-grid.{{ intDomain }}.{{ siteDomain }}" 
        state=present
  when: hostvars[item].int_ip_addr is defined and hosts_file_grid_group_to_populate != ""
  with_items: "{{ hosts_file_grid_group_to_populate }}"
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate hosts file with the install host's internal address
  lineinfile: 
        dest='{{ hosts_file_to_populate }}'
        regexp='^{{ hostvars[item].int_ip_addr }} {{ siteName }}-install {{item}} {{ siteName }}-install.{{ intDomain }}.{{ siteDomain }}$' 
        line="{{ hostvars[item].int_ip_addr }} {{ siteName }}-install {{item}} {{ siteName }}-install.{{ intDomain }}.{{ siteDomain }}" 
        state=present
  when: hostvars[item].int_ip_addr is defined and hosts_file_install_group_to_populate != ""
  with_items: "{{ hosts_file_install_group_to_populate }}"
  notify:
    - restart dnsmasq
  tags: dns_update

- name: populate hosts file with the login host's internal address
  lineinfile: 
        dest='{{ hosts_file_to_populate }}'
        regexp='^{{ hostvars[item].int_ip_addr }} {{ siteName }} {{item}} {{ siteName }}.{{ intDomain }}.{{ siteDomain }}$' 
        line="{{ hostvars[item].int_ip_addr }} {{ siteName }} {{item}} {{ siteName }}.{{ intDomain }}.{{ siteDomain }}" 
        state=present
  when: hostvars[item].int_ip_addr is defined and hosts_file_login_group_to_populate != ""
  with_items: "{{ hosts_file_login_group_to_populate }}"
  notify:
    - restart dnsmasq
  tags: dns_update

- name: copy over kickstart file
  template: src="kickstart.cfg" dest="{{ ksBootSrvDir }}/{{ hostvars[item].kickstart_profile }}" owner=apache group=apache mode=0644
  with_items: "{{ groups.pxe_bootable_nodes }}"
