---

#Local
#Generate SSH keys locally where you run ansible
- name: create SSH host key directory in files/nodes/nodename/ssh
  file: "path=files/nodes/{{ item }}/ssh state=directory recurse=yes"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: generate SSH RSA host keys for the nodes
  command: /usr/bin/ssh-keygen -t rsa -f files/nodes/{{ item }}/ssh/ssh_host_rsa_key -N "" -C "" creates=files/nodes/{{ item }}/ssh/ssh_host_rsa_key.pub
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: generate SSH ecdsa host keys for the nodes
  command: /usr/bin/ssh-keygen -t ecdsa -f files/nodes/{{ item }}/ssh/ssh_host_ecdsa_key -N "" -C "" creates=files/nodes/{{ item }}/ssh/ssh_host_ecdsa_key.pub
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: generate SSH ed25519 host keys for the nodes
  command: /usr/bin/ssh-keygen -t ed25519 -f files/nodes/{{ item }}/ssh/ssh_host_ed25519_key -N "" -C "" creates=files/nodes/{{ item }}/ssh/ssh_host_ed25519_key.pub
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write rsa pub keys into a known_hosts
  known_hosts: path='files/nodes/ssh_rsa_known_hosts'
               name='{{ item }}'
               key="{{ item }},{{ ip_address }},{{ ib_ip_addr }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_rsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ecdsa pub keys into a known_hosts
  known_hosts: path='files/nodes/ssh_ecdsa_known_hosts'
               name='{{ item }}'
               key="{{ item }},{{ ip_address }},{{ ib_ip_addr }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ecdsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ed25519 pub keys into a known_hosts
  known_hosts: path='files/nodes/ssh_ed25519_known_hosts'
               name='{{ item }}'
               key="{{ item }},{{ ip_address }},{{ ib_ip_addr }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ed25519_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes
